name: End-to-end tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  # Runs the end-to-end test suite.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the runner container.
  # - Installs NodeJS
  # - Sets up caching for NPM.
  # - Installs NPM dependencies.
  # - Starts the WordPress Docker container (wp-env FTW 🎉)
  # - Logs the running Docker containers.
  # - Logs WordPress debug information.
  # - Logs general debug information.
  # - Logs Docker debug information (about both the Docker installation within the runner and the WordPress container)
  # - Install WordPress within the Docker container.
  # - Run the E2E tests.
  e2e-tests:
    name: WP ${{ matrix.wp }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        include:
          - env_1: 'WordPress 5.1 on PHP 7.2'
            php: '7.2'
            wp: '5.1'
          - env_2: 'WordPress 5.2 on PHP 7.2'
            php: '7.2'
            wp: '5.1'
          - env_3: 'WordPress 5.3 on PHP 7.3'
            php: '7.3'
            wp: '5.3'
          - env_4: 'WordPress 5.4 on PHP 7.3'
            php: '7.3'
            wp: '5.4'
          - env_5: 'WordPress 5.5 on PHP 7.4'
            php: '7.4'
            wp: '5.5'
          - env_6: 'WordPress 5.6 on PHP 7.4'
            php: '7.4'
            wp: '5.6'
          - env_7: 'WordPress 5.7 on PHP 7.4'
            php: '7.4'
            wp: '5.7'
          - env_8: 'Latest version of WordPress on PHP 7.4'
            php: '7.4'
            wp: 'latest'
          - env_9: 'Latest version of WordPress on PHP 8'
            php: '8.0'
            wp: 'latest'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Output env information
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wp }}
        run: |
          if [[ $WP_VERSION == "latest" ]]; then export WP_CORE="null"; else export WP_CORE="\"WordPress/WordPress#$WP_VERSION\""; fi
          echo "{ \"core\": $WP_CORE, \"plugins\": [\".\"], \"phpVersion\": \"$PHP_VERSION\" }" > .wp-env.json

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version
          php --version
          php -i
          locale -a

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache NodeJS modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install

      - name: Start WordPress environment
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: |
          WP_ENV_PHP_VERSION=$PHP_VERSION npx wp-env start
          npx wp-env run cli "wp user create sucuri sucuri@sucuri.net --role=author --user_pass=password"
          npx wp-env run cli "wp rewrite structure '/%year%/%monthnum%/%postname%/'"

      - name: Log running Docker containers
        run: docker ps -a

      - name: Log WordPress debug information
        run: npx wp-env run cli wp core version

      - name: General debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Docker debug information
        run: docker -v

      - name: Run Sucuri Scanner tests (E2E)
        run: |
          cp cypress.json.example cypress.json
          npx cypress run --spec cypress/integration/sucuri-scanner.js

      - name: Run Firewall tests (E2E)
        if: env.cypress_waf_api_key
        env:
          cypress_waf_api_key: ${{ secrets.WAF_API_KEY }}
        run: npx cypress run --spec cypress/integration/sucuri-scanner-firewall.js
          
      - name: Upload Cypress tests on failure
        uses: actions/upload-artifact@v2.2.1
        if: failure()
        with:
          name: cypress
          path: |
            cypress/videos
            cypress/screenshots
        
